version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: cinefluent_db_simple
    restart: unless-stopped
    environment:
      POSTGRES_DB: cinefluent
      POSTGRES_USER: cinefluent_user
      POSTGRES_PASSWORD: cinefluent_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_simple:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cinefluent_user -d cinefluent"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_simple:
    driver: local
