services:
  db:
    image: postgres:16
    container_name: cinefluent_db
    environment:
      POSTGRES_DB: cinefluent
      POSTGRES_USER: cinefluent_user
      POSTGRES_PASSWORD: cinefluent_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cinefluent_user -d cinefluent"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: cinefluent_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: